name: config-schema-build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'question-generator/generators/index.ts'
      - 'question-generator/generators/**/index.ts'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
      with:
          token: ${{ secrets.BOT_PAT }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn ci
    - name: Generate Schema
      run: |
        yarn workspace question-generator generate-schema
    - name: Commit Schema
      run: |
        git config --global user.name 'Cody Duong'
        git config --global user.email 'codyduongbot@users.noreply.github.com'
        git fetch --all
        git add .
        git commit -am "Automated Schema Build"
        git push